### ISSUE TITLE
RemoteMediator is unusable right now

### ISSUE THREAD

**Issue by chrisbanes** [cashapp/multiplatform-paging#117]
Unfortunately RemoteMediator isn't usable right now. The return type needs to be a `RemoteMediatorMediatorResult` but the sealed class has no subclasses. This means that you can't create a `RemoteMediatorMediatorResultSuccess` or `RemoteMediatorMediatorResultError`

**Comment by chrisbanes** [comment]
Ah I was hitting https://github.com/cashapp/multiplatform-paging/tree/main/paging-common#superclass-removed-for-nested-classes-in-commonmain-only. Closing

**Comment by JohanAlbrectsen** [comment]
@chrisbanes 
How did you solve this if I may ask?

**Comment by chrisbanes** [comment]
See here: https://github.com/chrisbanes/tivi/blob/c5baaeaeb1e7f400efd601d8b666403918076a48/domain/src/commonMain/kotlin/app/tivi/domain/PaginatedEntryRemoteMediator.kt

**Comment by JohanAlbrectsen** [comment]
@chrisbanes 
Thank you so so much!
