### ISSUE TITLE
Support for ios() iosX64() architecture missing all libraries for those are not published

### ISSUE THREAD

**Issue by aadeshmindtickle** [cashapp/multiplatform-paging#120]
Hello,
        I want to use this library in my project which has support for following architectures:
        `
        iosX64()
        iosArm64()
        iosSimulatorArm64()`
        
        but this library gives error which used in my KMM project. Error stack 
        
         ```
> Task :widget:compileKotlinIosSimulatorArm64 FAILED
e: Could not find "org.jetbrains.kotlin.native.platform.CoreFoundationBase" in [/Users/Documents/felix, /Users/.konan/klib, /Users/.konan/kotlin-native-prebuilt-macos-aarch64-1.7.21/klib/common, /Users/.konan/kotlin-native-prebuilt-macos-aarch64-1.7.21/klib/platform/ios_simulator_arm64]

FAILURE: Build failed with an exception.
```

**Comment by aadeshmindtickle** [comment]
I found the actual reason for the error.
paging library 3.1.1-0.2.0 is using kotlin version 1.8.10. My app is configured for kotlin version 1.7.21 thus creating this issue. Verified above conclusion by setting kotlin version in toml file as 1.7.21 in repo-search sample.

There are 2 solution / work around for solving this issue:

Solution 1: 
    Update kotlin version of your project to 1.8.21 or above and you'll not face issue in running on iOS for above architectures as well.
    
Solution 2: 
        * use implementation("app.cash.paging:paging-common:3.1.1-0.1.1") in grade file 
        * also put optIn("androidx.paging.ExperimentalPagingApi") inside grades sourceSet
        
        Above steps solves issue in iOS but creates problem in android if you are using RemoteMediater by overriding this class.  
        Solution to fix this issue:
       * Fork this repo
       * Check a with tag 3.1.1.-0.1.1
       * Create a new branch fro this tag
       * cherry pick commit from https://github.com/cashapp/multiplatform-paging/pull/46/files
       * publish it as 3.1.1-0.1.2
       * use implementation("app.cash.paging:paging-common:3.1.1-0.1.2") in grade file

**Comment by veyndan** [comment]
Thanks for the report. Out of curiosity, is there a practical reason for not just upgrading your project to use Kotlin 1.8.21?

**Comment by aadeshmindtickle** [comment]
@veyndan there was some syntax related issue and also some 3rd party libraries issue in my project; to be able to update to Kotlin v 1.8.21. Anyways will be solving those issue and working towards updating to latest version.

Meanwhile you can update the readme of this repo:

Minimum kotlin version supported for this library is 1.8.21 to be able to use in iOS

**Comment by veyndan** [comment]
Closing this one out. Hopefully, if anyone is facing a similar issue, they'll come across this issue and see your workarounds listed above 😄
