### ISSUE TITLE
Web support for paging-runtime-composeui

### ISSUE THREAD

**Issue by kadirkid** [cashapp/multiplatform-paging#149]
Currently `paging-runtime-composeui` doesn't support web so is there any plans to add support?
If yes, are you open to outside contribution for this?
If no, why?

**Comment by veyndan** [comment]
`paging-runtime-composeui` is officially deprecated, as all the functions within the module has been marked with `@Deprecated` (as of [3.2.0-alpha05-0.2.1](https://github.com/cashapp/multiplatform-paging/releases/tag/3.2.0-alpha05-0.2.1)). The module will be removed in an upcoming release.

You _should_ be able to use `paging-compose-common` with web however (it already has a JS target), using the mechanism outlined in [these release notes under "Supporting all lazy layouts"](https://developer.android.com/jetpack/androidx/releases/paging#1.0.0-alpha19). Please let me know if you have any issues with that method!
