### ISSUE TITLE
Usage difference between paging-compose and paging-runtime-uikit

### ISSUE THREAD

**Issue by musooff** [cashapp/multiplatform-paging#175]
What is the usage difference between `paging-compose` and `paging-runtime-uikit`?

I am only targeting Android and iOS using compose Multiplatform.

When I show paging data in my composable with `paging-compose`, I don't see any need for `paging-runtime-uikit`.
It works fine both on Android and iOS.

According to the documentation `paging-runtime` of android as well is not necessary for compose based apps, since it only holds `PagingAdapter`.

So it all comes down to `paging-common` && `paging-compose` for compose multiplatform app, right?

**Comment by veyndan** [comment]
> What is the usage difference between `paging-compose` and `paging-runtime-uikit`?

If you're **_not_** using Compose on iOS, then you'll probably want `paging-runtime-uikit`. `paging-runtime-uikit` facilitates the consumption of paging events within a `UICollectionView`, which is desirable if you're doing plain iOS/UIKit stuff. If you're using Compose on iOS, then you don't need this module at all, as you're not working with `UICollectionView`.

> According to the documentation `paging-runtime` of android as well is not necessary for compose based apps, since it only holds `PagingAdapter`.

As you said, you don't need `paging-runtime` on Android if you're using Compose. Similarly to the `paging-runtime-uikit` argument, the module is only needed if you're doing plain Android/View stuff.

> So it all comes down to `paging-common` && `paging-compose[-common]` for compose multiplatform app, right?

Exactly!
