### ISSUE TITLE
Room Dao PagingSource compile time error

### ISSUE THREAD

**Issue by abduqahhoruz** [cashapp/multiplatform-paging#293]
@Query("SELECT * FROM PositionEntity WHERE product_type = 'null' ORDER BY autoId DESC")
    suspend fun getPositionPagedNoCat(): PagingSource<Int, PositionEntity>  Not sure how to convert a Cursor to this method's return type (androidx.paging.PagingSource

**Comment by H4kt** [comment]
There is already an issue regarding this on google issue tracker
https://issuetracker.google.com/issues/339934824
