### ISSUE TITLE
Not found `androidx.paging` (`LazyPagingItems` and `collectAsLazyPagingItems`) in `common` and `desktop` module

### ISSUE THREAD

**Issue by VitalyPeryatin** [cashapp/multiplatform-paging#3]
`common` module:
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/22561563/202373818-59d48cd4-1800-401b-904b-9af7f3d0e30a.png">

`desktop` module:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/22561563/202376505-1c8d2cb3-15c6-4ee3-83b1-dc4570db2924.png">

**Comment by veyndan** [comment]
The issue looks like you're not using Multiplatform Paging! In `commonMain`, if the package name is `app.cash.paging`, then it's from Multiplatform Paging, and if the package name is `androidx.paging`, it's not from us and is instead from the official AndroidX Paging artifact (which won't compile as it's not multiplatform!).

Unfortunately, changing the package name in your code won't help as:

1. You're using the `paging-compose` artifact, and Multiplatform Paging doesn't have a `paging-compose` artifact yet. We just have the artifacts `paging-common` and `paging-runtime`.
2. Multiplatform Paging doesn't target desktop yet. It just targets Android and iOS.

I'm going to close this issue and create two separate issues for the above points as they're independent.
