### ISSUE TITLE
Add support for `paging-compose`

### ISSUE THREAD

**Issue by veyndan** [cashapp/multiplatform-paging#4]
`paging-compose` only consists of the file [LazyPagingItems.kt](https://github.com/androidx/androidx/blob/androidx-main/paging/paging-compose/src/main/java/androidx/paging/compose/LazyPagingItems.kt), and the only part that is Android specific are [these lines](https://github.com/androidx/androidx/blob/6571b15822a6371389176ff9f56bf213ea2f627e/paging/paging-compose/src/main/java/androidx/paging/compose/LazyPagingItems.kt#L283-L381), which are basic UI bindings to the rest of the code. The rest of the file just uses Compose and could be relocated to `commonMain` and shared across platforms.

Ultimately, it'd be cool to add some bindings that integrate with [Compose Multiplatform](https://www.jetbrains.com/lp/compose-mpp/), but for now just add `paging-compose` support would be useful for those using Compose.

Note: I mean [Compose and not Compose UI](https://jakewharton.com/a-jetpack-compose-by-any-other-name/).

**Comment by ashdavies** [comment]
This would be really useful, even the Android specific lines appear to only use `Parcelable` for the placeholder key, which could potentially be abstracted out.

**Comment by veyndan** [comment]
The Android specific lines depend on Compose UI specific things as well (e.g., `androidx.compose.foundation.lazy.LazyListScope`). The goal of this is to just depend on Compose. A use case I'm imagining is being able to depend on `paging-compose` in the presenter layer so one doesn't have to mix business logic and display logic (and then it can play nicely with [cashapp/molecule](https://github.com/cashapp/molecule)).

Multiplatform Compose UI support (which would multiplatformize the Android specific lines) is currently being implemented in #9 though!

**Comment by crocsandcoffee** [comment]
Closing this PR and reopened a different one https://github.com/cashapp/multiplatform-paging/pull/14

**Comment by crocsandcoffee** [comment]
Multiplatform Compose UI support has been added in this PR https://github.com/cashapp/multiplatform-paging/pull/14
