### ISSUE TITLE
Clarification about how to use the experimental APIs

### ISSUE THREAD

**Issue by hichamboushaba** [cashapp/multiplatform-paging#6]
The library creates a new experimental annotation `app.cash.paging.ExperimentalPagingApi`, but when trying to use it, the compilation fails, the IDE and gradle complains:
```
This declaration needs opt-in. Its usage must be marked with '@androidx.paging.ExperimentalPagingApi' or '@OptIn(androidx.paging.ExperimentalPagingApi::class)'
```

Notice that it references to the `androidx.paging` annotation, I was able to solve this by adding the following to my gradle file:

```gradle
sourceSets {
    all {
        languageSettings.optIn("androidx.paging.ExperimentalPagingApi")
    }
}
```

But I think this point needs some clarifications, it's either a bug that needs to be solved, or if it's not, then it should be pointed in the documentation.

**Comment by veyndan** [comment]
Thanks @hichamboushaba for reporting this! As you mentioned, the library is _creating_ the `app.cash.paging.ExperimentalPagingApi` annotation. It should instead be _typealiasing_ to `androidx.paging.ExperimentalPagingApi`, like it does for the rest of the APIs.
