### ISSUE TITLE
`PagingData.map` not found

### ISSUE THREAD

**Issue by iruizmar** [cashapp/multiplatform-paging#7]
Hey! 👋🏻 

Thanks for the library :). It's super useful.

`PagingData` is not exposing any `map` function so it's quite difficult to map items inside.

Thanks! 🙇🏻

**Comment by veyndan** [comment]
Hi! Did you import the `map` function with `import app.cash.paging.map`?

**Comment by iruizmar** [comment]
Hey @veyndan! Thanks for your answer. That was exactly the problem.
The library is a bit hard to use because of #5. The import was not suggested by the IDE.
Thank you!
