### ISSUE TITLE
Consider renaming `paging-runtime` to `paging-runtime-uikit`

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/multiplatform-paging#8]
The runtimes are specific to a target **and** a target UI toolkit. For the JVM you could have ones like `paging-runtime-swing`, `paging-runtime-composeui`, etc. since there are multiple toolkits and you wouldn't want to package both inside a single, multiplatform `paging-runtime` which targets the JVM.

Basically, same rationale for how we named Redwood artifacts.

**Comment by JakeWharton** [comment]
And artifact like `paging-runtime-composeui` could themselves be multiplatform targeting Android and JVM which would help solve #4

**Comment by ahna92** [comment]
I've getting `Could not find app.cash.paging:paging-runtime-uikit:3.1.1-0.1.1` 

but when using `app.cash.paging:paging-runtime:3.1.1-0.1.1` it is working fine

i think need to publish new artifacts release with new name
